# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analytic.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='analytic.proto',
  package='analyticframework',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x61nalytic.proto\x12\x11\x61nalyticframework\"Q\n\x0bInputStream\x12\x0e\n\x06stream\x18\x01 \x01(\x0c\x12\x19\n\x11start_time_millis\x18\x02 \x01(\x03\x12\x17\n\x0f\x65nd_time_millis\x18\x03 \x01(\x03\"b\n\x10RegionOfInterest\x12\x0e\n\x06pixels\x18\x01 \x03(\x03\x12\x16\n\x0e\x63lassification\x18\x02 \x01(\t\x12\x12\n\ncondifence\x18\x03 \x01(\x02\x12\x12\n\nsupplement\x18\x04 \x01(\t\"\x8f\x01\n\x0fProcessedStream\x12\x0e\n\x06stream\x18\x01 \x01(\x0c\x12\x13\n\x0bstart_frame\x18\x02 \x01(\x03\x12\x11\n\tend_frame\x18\x03 \x01(\x03\x12\x12\n\noperations\x18\x04 \x03(\t\x12\x30\n\x03roi\x18\x05 \x03(\x0b\x32#.analyticframework.RegionOfInterest\"A\n\nInputFrame\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\x12\x11\n\tframe_num\x18\x02 \x01(\x03\x12\x11\n\ttimestamp\x18\x03 \x01(\x02\"=\n\tFrameData\x12\x30\n\x03roi\x18\x01 \x03(\x0b\x32#.analyticframework.RegionOfInterest2\xba\x01\n\x08\x41nalytic\x12\\\n\x12ProcessVideoStream\x12\x1e.analyticframework.InputStream\x1a\".analyticframework.ProcessedStream(\x01\x30\x01\x12P\n\x11ProcessVideoFrame\x12\x1d.analyticframework.InputFrame\x1a\x1c.analyticframework.FrameDatab\x06proto3')
)




_INPUTSTREAM = _descriptor.Descriptor(
  name='InputStream',
  full_name='analyticframework.InputStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream', full_name='analyticframework.InputStream.stream', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_time_millis', full_name='analyticframework.InputStream.start_time_millis', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_time_millis', full_name='analyticframework.InputStream.end_time_millis', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=118,
)


_REGIONOFINTEREST = _descriptor.Descriptor(
  name='RegionOfInterest',
  full_name='analyticframework.RegionOfInterest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pixels', full_name='analyticframework.RegionOfInterest.pixels', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='classification', full_name='analyticframework.RegionOfInterest.classification', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='condifence', full_name='analyticframework.RegionOfInterest.condifence', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='supplement', full_name='analyticframework.RegionOfInterest.supplement', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=218,
)


_PROCESSEDSTREAM = _descriptor.Descriptor(
  name='ProcessedStream',
  full_name='analyticframework.ProcessedStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream', full_name='analyticframework.ProcessedStream.stream', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_frame', full_name='analyticframework.ProcessedStream.start_frame', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_frame', full_name='analyticframework.ProcessedStream.end_frame', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='operations', full_name='analyticframework.ProcessedStream.operations', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='roi', full_name='analyticframework.ProcessedStream.roi', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=364,
)


_INPUTFRAME = _descriptor.Descriptor(
  name='InputFrame',
  full_name='analyticframework.InputFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame', full_name='analyticframework.InputFrame.frame', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame_num', full_name='analyticframework.InputFrame.frame_num', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='analyticframework.InputFrame.timestamp', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=366,
  serialized_end=431,
)


_FRAMEDATA = _descriptor.Descriptor(
  name='FrameData',
  full_name='analyticframework.FrameData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='roi', full_name='analyticframework.FrameData.roi', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=433,
  serialized_end=494,
)

_PROCESSEDSTREAM.fields_by_name['roi'].message_type = _REGIONOFINTEREST
_FRAMEDATA.fields_by_name['roi'].message_type = _REGIONOFINTEREST
DESCRIPTOR.message_types_by_name['InputStream'] = _INPUTSTREAM
DESCRIPTOR.message_types_by_name['RegionOfInterest'] = _REGIONOFINTEREST
DESCRIPTOR.message_types_by_name['ProcessedStream'] = _PROCESSEDSTREAM
DESCRIPTOR.message_types_by_name['InputFrame'] = _INPUTFRAME
DESCRIPTOR.message_types_by_name['FrameData'] = _FRAMEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InputStream = _reflection.GeneratedProtocolMessageType('InputStream', (_message.Message,), dict(
  DESCRIPTOR = _INPUTSTREAM,
  __module__ = 'analytic_pb2'
  # @@protoc_insertion_point(class_scope:analyticframework.InputStream)
  ))
_sym_db.RegisterMessage(InputStream)

RegionOfInterest = _reflection.GeneratedProtocolMessageType('RegionOfInterest', (_message.Message,), dict(
  DESCRIPTOR = _REGIONOFINTEREST,
  __module__ = 'analytic_pb2'
  # @@protoc_insertion_point(class_scope:analyticframework.RegionOfInterest)
  ))
_sym_db.RegisterMessage(RegionOfInterest)

ProcessedStream = _reflection.GeneratedProtocolMessageType('ProcessedStream', (_message.Message,), dict(
  DESCRIPTOR = _PROCESSEDSTREAM,
  __module__ = 'analytic_pb2'
  # @@protoc_insertion_point(class_scope:analyticframework.ProcessedStream)
  ))
_sym_db.RegisterMessage(ProcessedStream)

InputFrame = _reflection.GeneratedProtocolMessageType('InputFrame', (_message.Message,), dict(
  DESCRIPTOR = _INPUTFRAME,
  __module__ = 'analytic_pb2'
  # @@protoc_insertion_point(class_scope:analyticframework.InputFrame)
  ))
_sym_db.RegisterMessage(InputFrame)

FrameData = _reflection.GeneratedProtocolMessageType('FrameData', (_message.Message,), dict(
  DESCRIPTOR = _FRAMEDATA,
  __module__ = 'analytic_pb2'
  # @@protoc_insertion_point(class_scope:analyticframework.FrameData)
  ))
_sym_db.RegisterMessage(FrameData)



_ANALYTIC = _descriptor.ServiceDescriptor(
  name='Analytic',
  full_name='analyticframework.Analytic',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=497,
  serialized_end=683,
  methods=[
  _descriptor.MethodDescriptor(
    name='ProcessVideoStream',
    full_name='analyticframework.Analytic.ProcessVideoStream',
    index=0,
    containing_service=None,
    input_type=_INPUTSTREAM,
    output_type=_PROCESSEDSTREAM,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ProcessVideoFrame',
    full_name='analyticframework.Analytic.ProcessVideoFrame',
    index=1,
    containing_service=None,
    input_type=_INPUTFRAME,
    output_type=_FRAMEDATA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ANALYTIC)

DESCRIPTOR.services_by_name['Analytic'] = _ANALYTIC

# @@protoc_insertion_point(module_scope)
